calculadora: calculadora.o funciones.o titulo.o
	g++ -o calculadora.o funciones.o titulo.o

calculadora.o: calculadora.cpp
	g++ -c calculadora.cpp
funciones.o: funciones.cpp
	g++ -c funciones.cpp
titulo.o: titulo.cpp
	g++ -c titulo.cpp
